### ISSUE TITLE
🐛 Bug Report: Docker-compose file not working properly (migration services not waiting for database boot)

### ISSUE THREAD

**Issue by mikenussbaumer** [amplication/amplication#2007]
### 📜 Description

When I downloaded the source code and started the application with docker-compose the migration services started to run before the database was running.

### 👟 Reproduction steps

1. Download source code from amplication
2. docker-compose up

### 👍 Expected behavior

The application runs with the database.

### 👎 Actual Behavior

The application failed to run and printed these errors because the migration service started before the database was up:

```
backend-db-1       | The files belonging to this database system will be owned by user "postgres".
backend-db-1       | This user must also own the server process.
backend-db-1       | 
backend-db-1       | The database cluster will be initialized with locale "en_US.utf8".
backend-db-1       | The default database encoding has accordingly been set to "UTF8".
backend-db-1       | The default text search configuration will be set to "english".
backend-db-1       | 
backend-db-1       | Data page checksums are disabled.
backend-db-1       | 
backend-db-1       | fixing permissions on existing directory /var/lib/postgresql/data ... ok
backend-db-1       | creating subdirectories ... ok
backend-db-1       | selecting dynamic shared memory implementation ... posix
backend-db-1       | selecting default max_connections ... 100
backend-db-1       | selecting default shared_buffers ... 128MB
backend-db-1       | selecting default time zone ... Etc/UTC
backend-db-1       | creating configuration files ... ok
backend-db-1       | running bootstrap script ... ok
backend-db-1       | performing post-bootstrap initialization ... ok
backend-migrate-1  | 
backend-migrate-1  | > db:init
backend-migrate-1  | > run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed
backend-migrate-1  | 
backend-migrate-1  | 
backend-migrate-1  | > db:migrate-save
backend-migrate-1  | > prisma migrate dev "--name" "initial version"
backend-migrate-1  | 
backend-migrate-1  | Prisma schema loaded from prisma/schema.prisma
backend-migrate-1  | Datasource "postgres": PostgreSQL database "undefined", schema "public" at "db:5432"
backend-migrate-1  | 
backend-migrate-1  | Error: P1001: Can't reach database server at `db`:`5432`
backend-migrate-1  | 
backend-migrate-1  | Please make sure your database server is running at `db`:`5432`.
backend-migrate-1  | npm ERR! code 1
backend-migrate-1  | npm ERR! path /app/server
backend-migrate-1  | npm ERR! command failed
backend-migrate-1  | npm ERR! command sh -c prisma migrate dev "--name" "initial version"
backend-migrate-1  | 
backend-migrate-1  | npm ERR! A complete log of this run can be found in:
backend-migrate-1  | npm ERR!     /root/.npm/_logs/2021-11-17T12_56_32_201Z-debug.log
backend-migrate-1  | ERROR: "db:migrate-save -- --name 'initial version'" exited with 1.
backend-migrate-1  | npm ERR! code 1
backend-migrate-1  | npm ERR! path /app/server
backend-migrate-1  | npm ERR! command failed
backend-migrate-1  | npm ERR! command sh -c run-s "db:migrate-save -- --name 'initial version'" db:migrate-up seed
backend-migrate-1  | 
backend-migrate-1  | npm ERR! A complete log of this run can be found in:
backend-migrate-1  | npm ERR!     /root/.npm/_logs/2021-11-17T12_56_32_630Z-debug.log
backend-migrate-1 exited with code 1
```

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Chrome

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mikenussbaumer** [comment]
After chatting with @mshidlov adding health checks solved the problem:

```
version: "3"
services:
  server:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    ports:
      - "${SERVER_PORT}:3000"
    environment:
      POSTGRESQL_URL: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432"
      BCRYPT_SALT: "${BCRYPT_SALT}"
      JWT_SECRET_KEY: "${JWT_SECRET_KEY}"
      JWT_EXPIRATION: "${JWT_EXPIRATION}"
    depends_on:
      - migrate
  migrate:
    build:
      context: .
      args:
        NPM_LOG_LEVEL: notice
    command: npm run db:init
    working_dir: /app/server
    environment:
      POSTGRESQL_URL: "postgres://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@db:5432"
      BCRYPT_SALT: "${BCRYPT_SALT}"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRESQL_DB_NAME}", "-U", "${POSTGRESQL_USER}" ]
      timeout: 45s
      interval: 10s
      retries: 10

volumes:
  postgres: ~
```
