### ISSUE TITLE
🐛 Bug Report: Helm charts migration jobs is restarting

### ISSUE THREAD

**Issue by mshidlov** [amplication/amplication#3331]
### What happened?

When a migration job pod is finished running with a successful status it clears itself after 30 seconds (`ttlSecondsAfterFinished: 30`). After the pod history is cleared a new migration job pod is starting although the restart policy is never.

Look into using initContainers to achieve the migration.

### What you expected to happen

The migration job pod should run only once when a new version is deployed.

### How to reproduce

1. Deploy master
2. Wait for the migration job pod to finish running
3. Wait 30 seconds and see a new pod is started

### Amplication version

^0.14.10

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment]
@shaharblanksela we should use `initContainers` for this kind of stuff, this way we don't need to manage the container lifecycle.

```yaml
      initContainers:
      - name: <name>
        image: <image>
        command: ["sh", "-c", "<prisma migration script>"; exit" ]
        ...
```
