### ISSUE TITLE
🐛 Bug Report: plugin `github actions` the trigger on push/commit to path not working

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#5938]
### What happened?

Currently, next to the `workflow_dispatch` trigger, a `push` trigger is used, where a path is also provided as a scope for that trigger, unfortunatly the trigger isn't working as expected.

Current:
```
on:
  push:
    branches: ["*"]
    paths: ["./apps/two-two"]
```

Fix - push:
```
on:
  push:
    branches: ["*"]
    paths: ["<base_path>/<service_name>/**"]
```

Fix - pull_request
```
on:
  pull_request:
    types: ["synchronize","closed"]
    branches: ["*"]
    paths: ["<base_path>/<service_name>/**"]
```

^ I'd opt for the last setup. 

### What you expected to happen

That the workflow was triggered in the way it was expected, with each commit within a certain directory.

### How to reproduce

Create a workflow based on the github actions plugin. And do a commit in the specific directory after the github actions workflow job.

### Amplication version

1.5.7

### Are you willing to submit PR?

Yes I am willing to submit a PR!
