### ISSUE TITLE
Client: Background image should be 60%

### ISSUE THREAD

**Issue by Leeyaacov** [amplication/amplication#707]
On my Apps page, the background image should be 60%.

```css
.applications__bg {
    background-size: 60%;
}
```
