### ISSUE TITLE
New Plugin: Backstage integration

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#8287]
A new plugin for backstage integration. 
The new plugin will be responsible for creating the yaml file by which the service can be registered and displayed in Backstage. 

Detailed description:
1. The yaml file should be called- catalog-info.yaml
2. The yaml file should be located at the root folder of the service (next to the 'src' folder)
3. As the first step, we would expose the service only. At the next step we can consider exposing the APIs as well.
4. The structure of the yaml file should be-
```
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Amplication-[service-name; type: strings of length at least 1, and at most 63, must consist of sequences of [a-z0-9A-Z] possibly separated by one of [-_.] ]
  description: Backend service which is auto-generated by Amplication. [Description of the service if there is one]
  labels:
    vendor: amplication
  annotations:
    github.com/project-slug: [GitHub repo of the service]
  tags:
    - ['Node.js' or '.NET']
  links:
    - url: https://app.amplication.com/[workspace id]/[project id]/[service id]
      title: Amplication Platform
      icon: [Amplication icon- The icon field value is meant to be a semantic key that will map to a specific icon that may be provided by an icon library (e.g. material-ui icons)]
spec:
  type: service
  lifecycle: production
  owner: dev-team
```

-----
More info- 
How to register Amplication backend service into Backstage (after generating the service (with the Backstage plugin) code - https://backstage.io/docs/features/software-catalog/#manually-register-components
https://backstage.io/docs/features/software-catalog/descriptor-format/
